### ISSUE TITLE
problem w eggs not properly changing to desired rarity/gatcha type

### ISSUE THREAD

**Issue by ektenngel** [MikeyTheA/PokeRogueModLoader#2]
When loading up the mod loader for the first time, everything else functions completely fine, other than the egg section of the cheats. shiny and hatch next wave works just fine. Both rarity (common, rare, ect) and the gatcha types do not function as intended.

https://github.com/MikeyTheA/PokeRogueModLoader/assets/173637189/28e058a5-e168-46cf-96a9-f2bb7082f7a9

**Comment by ektenngel** [comment]
if needed i can provide a video of the gatcha types not functioning as well, but essentially that is the current bug/oversight i know of ehe

**Comment by MikeyTheA** [comment]
they've changed the tier in the egg class to _tier and changed the gacha type system or something, will be fixed once website is released (later today)

**Comment by ektenngel** [comment]
ohh!! i thought so, i was checking through the discord earlier and saw the same issue popping up, was assuming it was something like that. thank you! i'll hold out til then :]

**Comment by MikeyTheA** [comment]
fixed in the new version of MikesUtilities on the [website](https://mokerogue.net/)
